DROP TABLE IF EXISTS foi_requests CASCADE;
DROP TABLE IF EXISTS repair_records CASCADE;
DROP TABLE IF EXISTS contractors CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;
DROP TABLE IF EXISTS properties CASCADE;